import blog_1 from '../../../assets/images/blog/blog-1.png';
import blog_2 from '../../../assets/images/blog/blog-2.png';
import blog_3 from '../../../assets/images/blog/blog-3.png';

export const blog = [
  {
    href: './blogInfo',
    src: blog_1,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 1,
  },
  {
    href: './blogInfo',
    src: blog_2,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 2,
  },
  {
    href: './blogInfo',
    src: blog_3,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 3,
  },
  {
    href: './blogInfo',
    src: blog_1,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 4,
  },
  {
    href: './blogInfo',
    src: blog_2,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 5,
  },
  {
    href: './blogInfo',
    src: blog_3,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 6,
  },
  {
    href: './blogInfo',
    src: blog_1,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 7,
  },
  {
    href: './blogInfo',
    src: blog_2,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 8,
  },
  {
    href: './blogInfo',
    src: blog_3,
    title: 'Nicoplanet',
    subtitle: 'Pineapple Saturn',
    date: '13.12.2022',
    text: 'Just a crazy mint explosion followed by some satisfying freezing tickles',
    id: 9,
  },
];
